---
- name: sample playbook
  hosts: servers
#  remote_user: fractal
#  become: true
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: latest
      become: yes
#    - name: service apache2 start
#      service:
#        name: apache2
#        state: started
#        become: yes
